=== NardineWilliam/XML---Labs/Labs1&2/Assignment 1/Employees.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2024 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="address">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="street"/>
				<xs:element ref="buildingNumber"/>
				<xs:element ref="region"/>
				<xs:element ref="city"/>
				<xs:element ref="country"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="addresses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="address" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="buildingNumber" type="xs:integer"/>
	<xs:element name="city" type="xs:string"/>
	<xs:element name="country" type="xs:string"/>
	<xs:element name="email" type="xs:string"/>
	
	<xs:element name="employee">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="phones"/>
				<xs:element ref="addresses"/>
				<xs:element ref="email"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="employees">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="employee" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="name" type="xs:string"/>
	
	<xs:element name="phone">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="phones">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="phone" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="region" type="xs:string"/>
	<xs:element name="street" type="xs:string"/>
</xs:schema>

=== NardineWilliam/XML---Labs/Labs1&2/Assignment 1/Employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "Employees.dtd">
<?xml-stylesheet type=“text/css” href=“styles.css”?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Employees.xsd">
	<employee>
		<name>Vera Holland</name>
		<phones>
			<phone type="home">456789</phone>
			<phone type="work">123456</phone>
			<phone type="mobile">487965</phone>
		</phones>
		<addresses>
			<address>
				<street>Main Street</street>
				<buildingNumber>15</buildingNumber>
				<region>East</region>
				<city>New York</city>
				<country>US</country>
			</address>
			<address>
				<street>First Street</street>
				<buildingNumber>97</buildingNumber>
				<region>West</region>
				<city>Chicago</city>
				<country>US</country>
			</address>
		</addresses>
		<email>vera.holland@gmail.com</email>
	</employee>
	<employee>
		<name>Mavis Patrick</name>
		<phones>
			<phone type="home">541276</phone>
			<phone type="work">145869</phone>
			<phone type="mobile">745265</phone>
		</phones>
		<addresses>
			<address>
				<street>Second Street</street>
				<buildingNumber>25</buildingNumber>
				<region>North</region>
				<city>London</city>
				<country>UK</country>
			</address>
		</addresses>
		<email>mavis.patrick@yahoo.com</email>
	</employee>
	<employee>
		<name>Beata Potter</name>
		<phones>
			<phone type="home">426598</phone>
			<phone type="work">321957</phone>
			<phone type="mobile">613487</phone>
		</phones>
		<addresses>
			<address>
				<street>Third Street</street>
				<buildingNumber>87</buildingNumber>
				<region>South</region>
				<city>Dallas</city>
				<country>US</country>
			</address>
			<address>
				<street>Fifth Street</street>
				<buildingNumber>14</buildingNumber>
				<region>West</region>
				<city>Dallas</city>
				<country>US</country>
			</address>
		</addresses>
		<email>beata.potter@gmail.com</email>
	</employee>
</employees>
